ODR\AdminBundle\Entity\LayoutMeta:
    type: entity
    table: odr_layout_meta
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        layoutName:
            type: string
            length: 64
            fixed: false
            nullable: false
            column: layout_name
        layoutDescription:
            type: text
            nullable: true
            column: layout_description

        isOfficial:
            type: boolean
            nullable: false
            column: is_official
        isSearchDefault:
            type: boolean
            nullable: false
            column: is_search_default
        isViewDefault:
            type: boolean
            nullable: false
            column: is_view_default
        isEditDefault:
            type: boolean
            nullable: false
            column: is_edit_default

        publicDate:
            type: datetime
            nullable: false
            column: public_date

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        layout:
            targetEntity: Layout
            cascade: {  }
            mappedBy: null
            inversedBy: layoutMeta
            joinColumns:
                layout_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
