ODR\AdminBundle\Entity\LayoutData:
    type: entity
    table: odr_layout_data
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        display_type:
            type: integer
            nullable: false
            default: 0
            column: display_type

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        layout:
            targetEntity: Layout
            cascade: {  }
            mappedBy: null
            inversedBy: layoutData
            joinColumns:
                layout_id:
                    referencedColumnName: id
            orphanRemoval: false

        theme:
            targetEntity: Theme
            cascade: {  }
            mappedBy: null
            inversedBy: layoutData
            joinColumns:
                theme_id:
                    referencedColumnName: id
            orphanRemoval: false

        dataTree:
            targetEntity: DataTree
            cascade: {  }
            mappedBy: null
            inversedBy: layoutData
            joinColumns:
                data_tree_id:
                    nullable: true
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
