ODR\AdminBundle\Entity\Layout:
    type: entity
    table: odr_layout
    gedmo:
        soft_deleteable:
            field_name: deletedAt

    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        isBaseLayout:
            type: boolean
            nullable: false
            column: is_base_layout
        isTableLayout:
            type: boolean
            nullable: false
            column: is_table_layout

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    oneToMany:
        layoutMeta:
            targetEntity: LayoutMeta
            cascade: { }
            mappedBy: layout
            inversedBy: null
            joinColumns:
                layout_meta_id:
                    referencedColumnName: id
            orphanRemoval: false

        layoutData:
            targetEntity: LayoutData
            cascade: { }
            mappedBy: layout
            inversedBy: null
            joinColumns:
                layout_data_id:
                    referencedColumnName: id
            orphanRemoval: false

        userLayoutPreferences:
            targetEntity: UserLayoutPreferences
            cascade: { }
            mappedBy: layout
            inversedBy: null
            joinColumns:
                user_layout_preferences_id:
                    referencedColumnName: id
            orphanRemoval: false

    manyToOne:
        dataType:
            targetEntity: DataType
            cascade: {  }
            mappedBy: null
            inversedBy: layouts
            joinColumns:
                data_type_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
