ODR\AdminBundle\Entity\UserLayoutPreferences:
    type: entity
    table: odr_user_layout_preferences
    gedmo:
        soft_deleteable:
            field_name: deletedAt
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY

        isHidden:
            type: boolean
            nullable: false
            column: is_hidden
        isSearchDefault:
            type: boolean
            nullable: false
            column: is_search_default
        isViewDefault:
            type: boolean
            nullable: false
            column: is_view_default
        isEditDefault:
            type: boolean
            nullable: false
            column: is_edit_default

        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true

    manyToOne:
        user:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        layout:
            targetEntity: Layout
            cascade: {  }
            mappedBy: null
            inversedBy: userLayoutPreferences
            joinColumns:
                layout_id:
                    referencedColumnName: id
            orphanRemoval: false

        createdBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                createdBy:
                    referencedColumnName: id
            orphanRemoval: false
        updatedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                updatedBy:
                    referencedColumnName: id
            orphanRemoval: false
        deletedBy:
            targetEntity: ODR\OpenRepository\UserBundle\Entity\User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                deletedBy:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
